name: easy_dialog
description: An easy custom dialog
version: 1.0.1
authors: 
- Ricardo Niño <ricardonior@gmail.com>
- Javier Duarte <javierandresduarte@gmail.com>

homepage: https://github.com/RicardoNino29/easy_dialog

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


